const fs = require('fs');
const file = 'src/i18n/index.ts';
let code = fs.readFileSync(file, 'utf8');

const reps = [
  { old: 'storyTitle: "POURQUOI JE FAIS CELA ?",', new: 'storyTitle1: "POURQUOI", storyTitle2: " JE FAIS CELA ?", manifestoTitle: "L\'Avant-Garde T\'Attend", manifestoText: "Le trading de détail est conçu pour vous faire échouer. Rejoignez l\'élite qui trade avec les données réelles et l\'Orderflow.", manifestoCta: "Rejoindre VALHALLA CAPITAL", legalMentions: "Mentions Légales", legalPrivacy: "Confidentialité", legalTerms: "CGU / CGV", legalRisk: "Divulgation des Risques", footerRisk: "AVERTISSEMENT SUR LES RISQUES : Le trading de CFD et Forex comporte un risque élevé. Valhalla Capital LLC opère sous la juridiction du Paraguay, conformément aux réglementations internationales en vigueur.",' },
  { old: 'storyTitle: "PERCHÉ FACCIO QUESTO?",', new: 'storyTitle1: "PERCHÉ", storyTitle2: " FACCIO QUESTO?", manifestoTitle: "L\'Avanguardia Ti Aspetta", manifestoText: "Il trading retail è progettato per farti fallire. Unisciti all\'élite che opera con dati reali e Orderflow.", manifestoCta: "Unisciti a VALHALLA CAPITAL", legalMentions: "Note Legali", legalPrivacy: "Privacy", legalTerms: "Termini e Condizioni", legalRisk: "Informativa sui Rischi", footerRisk: "AVVERTENZA SUI RISCHI: Il trading di CFD e Forex comporta un rischio elevato. Valhalla Capital LLC opera sotto la giurisdizione del Paraguay.",' },
  { old: 'storyTitle: "¿POR QUÉ HAGO ESTO?",', new: 'storyTitle1: "¿POR QUÉ", storyTitle2: " HAGO ESTO?", manifestoTitle: "La Vanguardia Te Espera", manifestoText: "El trading retail está diseñado para que fracases. Únete a la élite que opera con datos reales y Orderflow.", manifestoCta: "Únete a VALHALLA CAPITAL", legalMentions: "Aviso Legal", legalPrivacy: "Privacidad", legalTerms: "Términos y Condiciones", legalRisk: "Divulgación de Riesgos", footerRisk: "ADVERTENCIA DE RIESGO: El trading de CFD y Forex conlleva un alto riesgo. Valhalla Capital LLC opera bajo la jurisdicción de Paraguay.",' },
  { old: 'storyTitle: "WARUM MACHE ICH DAS?",', new: 'storyTitle1: "WARUM", storyTitle2: " MACHE ICH DAS?", manifestoTitle: "Die Avantgarde Erwartet Dich", manifestoText: "Retail-Trading ist darauf ausgelegt, dass Sie scheitern. Schließen Sie sich der Elite an, die mit echten Daten und Orderflow tradet.", manifestoCta: "VALHALLA CAPITAL Beitreten", legalMentions: "Impressum", legalPrivacy: "Datenschutz", legalTerms: "AGB", legalRisk: "Risikohinweis", footerRisk: "RISIKOHINWEIS: Der Handel mit CFDs und Forex ist mit einem hohen Risiko verbunden. Valhalla Capital LLC operiert unter der Gerichtsbarkeit von Paraguay.",' },
  { old: 'storyTitle: "ПОЧЕМУ Я ЭТО ДЕЛАЮ?",', new: 'storyTitle1: "ПОЧЕМУ", storyTitle2: " Я ЭТО ДЕЛАЮ?", manifestoTitle: "Авангард Ждет Тебя", manifestoText: "Ритейл-трейдинг создан для того, чтобы вы терпели неудачу. Присоединяйтесь к элите, торгующей на реальных данных и Orderflow.", manifestoCta: "Присоединиться к VALHALLA CAPITAL", legalMentions: "Юридическая Информация", legalPrivacy: "Конфиденциальность", legalTerms: "Условия Использования", legalRisk: "Уведомление о Рисках", footerRisk: "ПРЕДУПРЕЖДЕНИЕ О РИСКАХ: Торговля CFD и Forex сопряжена с высоким риском. Valhalla Capital LLC действует под юрисдикцией Парагвая.",' },
  { old: 'storyTitle: "なぜこれを行うのか？",', new: 'storyTitle1: "なぜ", storyTitle2: " これを行うのか？", manifestoTitle: "アバンギャルドがあなたを待っています", manifestoText: "リテール取引はあなたが失敗するように設計されています。実際のデータとオーダーフローで取引するエリートに参加してください。", manifestoCta: "VALHALLA CAPITALに参加", legalMentions: "法的通知", legalPrivacy: "プライバシー", legalTerms: "利用規約", legalRisk: "リスク開示", footerRisk: "リスク警告：CFDおよびForexの取引には高いリスクが伴います。Valhalla Capital LLCはパラグアイの管轄下で運営されています。",' }
];

for (const r of reps) {
  code = code.replace(r.old, r.new);
}
fs.writeFileSync(file, code);
console.log("Done");
